name: AWS deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write # This is required for requesting the JWT

env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java and Gradle
        uses: ./.github/actions/setup-java-gradle # Usa la acción compuesta
        with:
          java-version: ${{ env.JAVA_VERSION }}
          gradle-version: ${{ env.GRADLE_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::237033183304:role/GitHubActionsRol
          aws-region: us-east-1
      - name: Test AWS Authentication
        run: |
          aws sts get-caller-identity